(in-package #:sql-query-postgres)

(defclass postgres-dialect (ansi-dialect) ())

(defun make-postgres-dialect ()
  (make-instance 'postgres-dialect))

(defmethod dialect-param-style ((dialect postgres-dialect)) :dollar)

(defmethod dialect-type-sql ((dialect postgres-dialect) type-spec)
  (cond
    ((null type-spec) "TEXT")
    ((stringp type-spec) type-spec)
    ((keywordp type-spec)
     (case type-spec
       ((:integer :int) "INTEGER")
       ((:bigint) "BIGINT")
       ((:smallint) "SMALLINT")
       ((:text :string) "TEXT")
       ((:boolean :bool) "BOOLEAN")
       ((:real :float) "REAL")
       ((:double) "DOUBLE PRECISION")
       ((:blob :bytea :binary) "BYTEA")
       ((:timestamp) "TIMESTAMP")
       ((:timestamptz) "TIMESTAMPTZ")
       ((:date) "DATE")
       ((:time) "TIME")
       ((:serial) "SERIAL")
       ((:numeric :decimal) "NUMERIC")
       (otherwise (call-next-method))))
    ((and (consp type-spec) (eq (first type-spec) :varchar))
     (format nil "VARCHAR(~a)" (second type-spec)))
    ((and (consp type-spec) (eq (first type-spec) :char))
     (format nil "CHAR(~a)" (second type-spec)))
    (t (call-next-method))))

(defmethod dialect-autoincrement-pk ((dialect postgres-dialect))
  "SERIAL PRIMARY KEY")

(defmethod dialect-autoincrement-suffix ((dialect postgres-dialect))
  "")

(defmethod emit-limit-offset ((dialect postgres-dialect) lim off stream ctx)
  (when lim
    (write-string " LIMIT " stream)
    (emit-sql dialect (lit (limit-count lim)) stream ctx))
  (when off
    (write-string " OFFSET " stream)
    (emit-sql dialect (lit (offset-count off)) stream ctx)))

(defmethod emit-returning ((dialect postgres-dialect) items stream ctx)
  (write-string " RETURNING " stream)
  (emit-column-list dialect items stream ctx))

(defmethod emit-for-update ((dialect postgres-dialect) clause stream ctx)
  (write-string " FOR UPDATE" stream)
  (when (for-update-of clause)
    (write-string " OF " stream)
    (emit-column-list dialect (for-update-of clause) stream ctx))
  (when (for-update-nowait clause) (write-string " NOWAIT" stream))
  (when (for-update-skip-locked clause) (write-string " SKIP LOCKED" stream)))

(defmethod emit-distinct ((dialect postgres-dialect) clause stream ctx)
  (write-string "DISTINCT " stream)
  (when (distinct-on clause)
    (write-string "ON (" stream)
    (emit-column-list dialect (distinct-on clause) stream ctx)
    (write-string ") " stream)))

(defmethod emit-column-def ((dialect postgres-dialect) col stream ctx)
  (emit-ident dialect (column-def-name col) stream)
  (write-char #\Space stream)
  (cond
    ((and (column-def-autoincrement col) (column-def-primary-key col))
     (write-string (dialect-autoincrement-pk dialect) stream))
    ((column-def-autoincrement col)
     (write-string "SERIAL" stream)
     (when (column-def-primary-key col) (write-string " PRIMARY KEY" stream)))
    (t
     (write-string (dialect-type-sql dialect (column-def-type col)) stream)
     (when (column-def-primary-key col) (write-string " PRIMARY KEY" stream))))
  (when (column-def-not-null col) (write-string " NOT NULL" stream))
  (when (column-def-unique col) (write-string " UNIQUE" stream))
  (when (column-def-default col)
    (write-string " DEFAULT " stream)
    (let ((d (column-def-default col)))
      (emit-sql dialect (if (typep d 'sql-node) d (lit d)) stream ctx))))

(defmethod emit-create-procedure ((dialect postgres-dialect) stmt stream ctx)
  (write-string "CREATE " stream)
  (when (create-procedure-or-replace stmt)
    (write-string "OR REPLACE " stream))
  (write-string "PROCEDURE " stream)
  (emit-ident dialect (create-procedure-name stmt) stream)
  (write-char #\( stream)
  (loop for (p . rest) on (create-procedure-params stmt)
        do (write-string (ecase (procedure-param-mode p)
                           (:in "IN ")
                           (:out "OUT ")
                           (:inout "INOUT "))
                         stream)
           (emit-ident dialect (procedure-param-name p) stream)
           (write-char #\Space stream)
           (write-string (dialect-type-sql dialect (procedure-param-type p)) stream)
           (when rest (write-string ", " stream)))
  (write-string ") LANGUAGE " stream)
  (write-string (ident-string (create-procedure-language stmt)) stream)
  (write-string " AS $$" stream)
  (write-string "BEGIN " stream)
  (loop for (form . rest) on (create-procedure-body stmt)
        do (emit-sql dialect form stream ctx)
           (write-char #\; stream)
           (when rest (write-char #\Space stream)))
  (write-string " END$$" stream))

;;; plpgsql control-flow emit (lispy BODY → IF/:=/LOOP/EXIT)

(defmethod emit-sql ((dialect postgres-dialect) (node proc-progn) stream ctx)
  (write-string "BEGIN " stream)
  (loop for (f . rest) on (proc-progn-forms node)
        do (emit-sql dialect f stream ctx)
           (write-char #\; stream)
           (when rest (write-char #\Space stream)))
  (write-string " END" stream))

(defmethod emit-sql ((dialect postgres-dialect) (node proc-let) stream ctx)
  (write-string "DECLARE " stream)
  (loop for (b . rest) on (proc-let-bindings node)
        do (destructuring-bind (name type &optional (default nil defaultp)) b
             (emit-ident dialect name stream)
             (write-char #\Space stream)
             (write-string (dialect-type-sql dialect type) stream)
             (when defaultp
               (write-string " := " stream)
               (emit-sql dialect default stream ctx))
             (when rest (write-string "; " stream))))
  (write-string "; BEGIN " stream)
  (loop for (f . rest) on (proc-let-forms node)
        do (emit-sql dialect f stream ctx)
           (write-char #\; stream)
           (when rest (write-char #\Space stream)))
  (write-string " END" stream))

(defmethod emit-sql ((dialect postgres-dialect) (node proc-setf) stream ctx)
  (let ((place (proc-setf-place node)))
    (emit-ident dialect
                (if (typep place 'column-ref)
                    (column-ref-name place)
                    place)
                stream))
  (write-string " := " stream)
  (emit-sql dialect (proc-setf-value node) stream ctx))

(defmethod emit-sql ((dialect postgres-dialect) (node proc-while) stream ctx)
  (write-string "WHILE " stream)
  (let ((test (proc-while-test node)))
    (if (proc-while-until node)
        (progn (write-string "NOT (" stream)
               (emit-sql dialect test stream ctx)
               (write-char #\) stream))
        (emit-sql dialect test stream ctx)))
  (write-string " LOOP " stream)
  (loop for (f . rest) on (proc-while-forms node)
        do (emit-sql dialect f stream ctx)
           (write-char #\; stream)
           (when rest (write-char #\Space stream)))
  (write-string " END LOOP" stream))

(defmethod emit-sql ((dialect postgres-dialect) (node proc-loop) stream ctx)
  (when (proc-loop-label node)
    (write-string (ident-string (proc-loop-label node)) stream)
    (write-string " : " stream))
  (write-string "LOOP " stream)
  (loop for (f . rest) on (proc-loop-forms node)
        do (emit-sql dialect f stream ctx)
           (write-char #\; stream)
           (when rest (write-char #\Space stream)))
  (write-string " END LOOP" stream))

(defmethod emit-sql ((dialect postgres-dialect) (node proc-return) stream ctx)
  (declare (ignore ctx))
  (write-string "EXIT" stream)
  (when (proc-return-label node)
    (write-char #\Space stream)
    (write-string (ident-string (proc-return-label node)) stream)))

(defmethod emit-sql ((dialect postgres-dialect) (node proc-cond) stream ctx)
  (let ((clauses (proc-cond-clauses node)))
    (loop for (clause . rest) on clauses
          for first = t then nil
          for test = (car clause)
          for forms = (cdr clause)
          do (cond
               ((and (null rest) (eq test t))
                (write-string " ELSE " stream)
                (loop for (f . r2) on forms
                      do (emit-sql dialect f stream ctx)
                         (write-char #\; stream)
                         (when r2 (write-char #\Space stream))))
               (first
                (write-string "IF " stream)
                (emit-sql dialect test stream ctx)
                (write-string " THEN " stream)
                (loop for (f . r2) on forms
                      do (emit-sql dialect f stream ctx)
                         (write-char #\; stream)
                         (when r2 (write-char #\Space stream))))
               (t
                (write-string " ELSIF " stream)
                (emit-sql dialect test stream ctx)
                (write-string " THEN " stream)
                (loop for (f . r2) on forms
                      do (emit-sql dialect f stream ctx)
                         (write-char #\; stream)
                         (when r2 (write-char #\Space stream))))))
    (write-string " END IF" stream)))

(defmethod emit-sql ((dialect postgres-dialect) (node proc-if) stream ctx)
  (write-string "IF " stream)
  (emit-sql dialect (proc-if-test node) stream ctx)
  (write-string " THEN " stream)
  (emit-sql dialect (proc-if-then node) stream ctx)
  (write-string "; " stream)
  (when (proc-if-else node)
    (write-string "ELSE " stream)
    (emit-sql dialect (proc-if-else node) stream ctx)
    (write-string "; " stream))
  (write-string "END IF" stream))

(defmethod emit-call ((dialect postgres-dialect) stmt stream ctx)
  (write-string "CALL " stream)
  (emit-ident dialect (call-name stmt) stream)
  (write-char #\( stream)
  (loop for (arg . rest) on (call-args stmt)
        do (cond
             ((typep arg 'binary-op)
              (emit-sql dialect (binary-op-right arg) stream ctx))
             (t (emit-sql dialect (ensure-expr arg) stream ctx)))
           (when rest (write-string ", " stream)))
  (write-char #\) stream))

(defmethod initialize-instance :after ((dialect postgres-dialect) &key)
  (register-postgres-extensions dialect))

(defun use-postgres-dialect ()
  "Register :postgres dialect (does not steal *SQL-DIALECT* unless unbound). Returns dialect."
  (let ((d (make-postgres-dialect)))
    (register-sql-dialect :postgres d)
    (unless *sql-dialect*
      (setf *sql-dialect* d))
    d))

(use-postgres-dialect)
